export type ProviderId = 'aws' | 'gcp' | 'azure' | 'hetzner';

export interface ResourceQuantity {
  cpuCores: number;
  memoryGiB: number;
}

export interface ContainerResources {
  name: string;
  image: string;
  cpuCores: number;
  memoryGiB: number;
  gpuCount: number;
  usedLimitsAsProxy: boolean;
  usedDefaults: boolean;
}

export interface ParsedWorkload {
  kind: string;
  name: string;
  namespace: string;
  replicas: number;
  containers: ContainerResources[];
  annotations?: Record<string, string>;
}

export interface ParsedPVC {
  name: string;
  namespace: string;
  storageGiB: number;
  storageClass?: string;
}

export interface ParsedService {
  name: string;
  namespace: string;
  type: string;
}

export interface ParsedIngress {
  name: string;
  namespace: string;
  ingressClass?: string;
}

export interface ParseResult {
  workloads: ParsedWorkload[];
  pvcs: ParsedPVC[];
  services: ParsedService[];
  ingresses: ParsedIngress[];
}

export interface PriceSheet {
  provider: ProviderId;
  service: string;
  region: string;
  as_of: string;
  /** Set when generated by `npm run refresh-pricing` from live APIs. */
  fetched_at?: string;
  sources: string[];
  hours_per_month: number;
  control_plane: {
    hourly_usd: number;
    tier?: string;
    free_zonal_cluster?: boolean;
    standard_hourly_usd?: number;
    notes?: string;
  };
  reference_instance: {
    type: string;
    vcpu: number;
    memory_gib: number;
    hourly_usd: number;
    notes?: string;
  };
  /** Smallest/common VMs for node-floor bin-packing (cheapest fit wins). */
  instance_catalog?: Array<{
    type: string;
    vcpu: number;
    memory_gib: number;
    hourly_usd: number;
  }>;
  rates: {
    cpu_per_vcpu_hour_usd: number;
    memory_per_gib_hour_usd: number;
    derivation?: string;
  };
  storage: Record<string, number | string> & {
    default_class?: string;
  };
  load_balancer_monthly_usd: number;
  /** Monthly fee per Ingress (cloud LB controller); 0 when not billed separately. */
  ingress_lb_monthly_usd?: number;
  /** Hetzner bills whole VPS instances — use node floor only for compute. */
  compute_model?: 'marginal_and_node' | 'node_only';
  defaults: {
    missing_cpu: string;
    missing_memory: string;
    daemonset_node_count: number;
  };
}

export interface MonthlyUsdRange {
  min: number;
  max: number;
}

export interface CostLineItem {
  category:
    | 'compute'
    | 'gpu'
    | 'storage'
    | 'load_balancer'
    | 'ingress'
    | 'control_plane';
  label: string;
  monthlyUsd: number;
  /** Set when min ≠ max (e.g. compute marginal vs node floor). */
  monthlyUsdRange?: MonthlyUsdRange;
}

export interface ProviderEstimate {
  provider: ProviderId;
  region: string;
  asOf: string;
  /** Conservative total for ranking (node floor + overhead). */
  totalMonthlyUsd: number;
  totalMonthlyUsdRange: MonthlyUsdRange;
  computeMonthlyUsdRange: MonthlyUsdRange;
  nodeCount: number;
  /** VM type selected for node-floor compute (from catalog). */
  nodeInstanceType: string;
  /** Set when workload requests GPUs. */
  gpuInstanceType?: string;
  gpuCount?: number;
  lineItems: CostLineItem[];
}

export type WarningSeverity = 'info' | 'warning' | 'error';

export interface Warning {
  id: string;
  severity: WarningSeverity;
  message: string;
  resource?: string;
}

export interface EstimateOptions {
  /** Use GKE free zonal cluster (zero control plane) */
  gkeFreeTier?: boolean;
  /** AKS tier: free (default) or standard */
  aksTier?: 'free' | 'standard';
  daemonsetNodeCount?: number;
  /** Minimum worker nodes for node-floor model (default 1). */
  minNodes?: number;
}

export type ConfidenceLevel = 'high' | 'medium' | 'low';

export interface ConfidenceResult {
  score: number;
  level: ConfidenceLevel;
  factors: string[];
}

export interface WorkloadSummary {
  kind: string;
  name: string;
  namespace: string;
  replicas: number;
  /** Total CPU cores requested (containers × replicas). */
  cpuCores: number;
  /** Total memory GiB requested (containers × replicas). */
  memoryGiB: number;
  gpuCount: number;
  /** Compute-only monthly cost range per provider (marginal .. node floor). */
  computeMonthlyUsdRange: Partial<Record<ProviderId, MonthlyUsdRange>>;
}

export interface GpuPriceSheetInstance {
  type: string;
  gpu_model: string;
  gpu_count: number;
  gpu_memory_gib: number;
  vcpu: number;
  memory_gib: number;
  hourly_usd: number;
  monthly_usd: number;
  source: string;
}

export interface GpuPriceSheet {
  provider: ProviderId;
  service: string;
  region: string;
  as_of: string;
  fetched_at: string;
  sources: string[];
  hours_per_month: number;
  currency: 'USD';
  eur_to_usd?: number;
  instances: GpuPriceSheetInstance[];
}

export interface EstimateResult {
  providers: ProviderEstimate[];
  warnings: Warning[];
  workloads: WorkloadSummary[];
  confidence: ConfidenceResult;
  totals: {
    cpuCores: number;
    memoryGiB: number;
    gpuCount: number;
    storageGiB: number;
    loadBalancerCount: number;
    ingressCount: number;
  };
}

/** Normalized GPU tier IDs used across marketplace providers. */
export type GpuTierId =
  | 't4-16gb'
  | 'l4-24gb'
  | 'a10g-24gb'
  | 'rtx4090-24gb'
  | 'a100-40gb'
  | 'a100-80gb'
  | 'h100-80gb';

export type MarketplaceProviderId =
  | 'runpod'
  | 'modal'
  | 'replicate'
  | 'lambda'
  | 'vast';

export type InferenceBillingMode = 'serverless' | 'pod';

export interface InferenceProfile {
  name: string;
  billing: InferenceBillingMode;
  gpu: GpuTierId;
  /** Catalog model id, e.g. llama-3.1-8b */
  model?: string;
  quantization?: string;
  contextLength?: number;
  concurrentUsers?: number;
  /** Override catalog default for $/1M token math */
  tokensPerSecond?: number;
  requestsPerDay: number;
  /** Founder-friendly: tokens per request (derives GPU seconds when set) */
  inputTokensPerRequest?: number;
  outputTokensPerRequest?: number;
  avgSecondsPerRequest: number;
  workers: number;
}

export type ApiProviderId = 'groq' | 'openai' | 'together';

export interface ApiModelPricing {
  catalog_id: string;
  api_model: string;
  label: string;
  input_per_million_usd: number;
  output_per_million_usd: number;
  source: string;
}

export interface ApiPriceSheet {
  provider: ApiProviderId;
  as_of: string;
  fetched_at: string;
  sources: string[];
  models: ApiModelPricing[];
}

export interface ApiProviderEstimate {
  provider: ApiProviderId;
  label: string;
  apiModel: string;
  asOf: string;
  totalMonthlyUsd: number;
  usdPerMillionTokens: number;
  inputPerMillionUsd: number;
  outputPerMillionUsd: number;
}

export interface FounderVerdict {
  kind: 'api' | 'gpu';
  providerLabel: string;
  monthlyUsd: number;
  headline: string;
  detail: string;
  planningMinUsd: number;
  planningMaxUsd: number;
}

export interface MarketplaceGpuTier {
  id: GpuTierId;
  label: string;
  gpu_model: string;
  gpu_memory_gib: number;
  /** Serverless $/second (scale-to-zero). */
  serverless_per_second_usd: number | null;
  /** On-demand pod/VM $/hour (always-on). */
  pod_per_hour_usd: number | null;
  source: string;
}

export interface MarketplacePriceSheet {
  provider: MarketplaceProviderId;
  as_of: string;
  fetched_at: string;
  sources: string[];
  hours_per_month: number;
  tiers: MarketplaceGpuTier[];
}

export interface MarketplaceProviderEstimate {
  provider: MarketplaceProviderId;
  asOf: string;
  totalMonthlyUsd: number;
  lineItems: CostLineItem[];
  matchedTier: string;
  billing: InferenceBillingMode;
  /** Derived: monthly cost / tokens per month × 1M */
  usdPerMillionTokens: number | null;
  /** Requests/day where pod billing equals serverless for this tier */
  podBreakEvenRequestsPerDay: number | null;
}

export interface InferenceModelSummary {
  id: string;
  label: string;
  quantization: string;
  totalVramGiB: number;
  minGpuTier: GpuTierId;
  tokensPerSecond: number;
}

export interface InferenceEstimateResult {
  profile: InferenceProfile;
  apiProviders: ApiProviderEstimate[];
  providers: MarketplaceProviderEstimate[];
  verdict: FounderVerdict;
  warnings: Warning[];
  model?: InferenceModelSummary;
  totals: {
    gpuTier: GpuTierId;
    requestsPerMonth: number;
    computeSecondsPerMonth: number;
    tokensPerMonth: number;
    workers: number;
    /** Cheapest option $/1M tokens (API or GPU) */
    usdPerMillionTokens: number | null;
  };
}
